version: "3"

services:
  #Configuration Sql Server
  company.database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: company.database
    environment:
      ACCEPT_EULA: "Y"
      SA_USER: "sa"
      SA_PASSWORD: "cz7YkLL09@!0*"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - company-network

  #Configuration Webapi
  company.api:
    build:
      context: Company
      dockerfile: Dockerfile
    image: company
    container_name: company.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
    networks:
      - company-network
    depends_on:
      - "company.database"

#Network for containers
networks:
  company-network:
    driver: bridge
