version: '3'

services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "6zY0KGaw"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  company-api:
    build: .
    ports:
      - "8080:80"